
platform :ios, '9.0'

inhibit_all_warnings!

target 'MKKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.4'
  pod 'SVProgressHUD'
  pod 'InputKit'
  
  pod 'Moya/RxSwift'
  pod 'RxCocoa'

end
